### ISSUE TITLE
large-video-upload-python async upload code does not working correctly.

### ISSUE THREAD

**Issue by royalwood** [twitterdev/large-video-upload-python#4]
```
{u'media_id_string': u'881896187762233346', u'media_id': 881896187762233346, u'processing_info': {u'check_after_secs': 5, u'state': u'pending'}, u'expires_after_secs': 86400, u'size': 10492221}
Media processing status is pending 
Checking after 5 seconds
STATUS
Media processing status is failed 
```
I got this error when trying upload 10MB video file to my twitter account.

any idea?

**Comment by smithaitufe** [comment]
@NodeUrsa Where you able to resolve this issue?

**Comment by Supertecnoboff** [comment]
I have the same issue too. The maximum video size limit of Twitter is 15 MB, so this doesn't make sense.

**Comment by andypiper** [comment]
In cases like these it would be really helpful to have example video files that we can attempt to reproduce the problem with. It sounds like the media processing step is failing post-upload, so my guess is that the file does not meet the encoding requirements for the media upload API, rather than this being anything to do with the size of the file.

**Comment by andypiper** [comment]
Given the lack of follow-up at this time I'm going to close this, but if you do find that this is an issue in the future please add more information and share example files for repro testing.
